#!/bin/bash

#退出上一个错误
set -e

#Openshift设置GIT_DIR为.若不是将报错为：
#"."不是GIT仓库。
unset GIT_DIR

#设置权限
umask 077

#载入全局
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

#设置程序版本
NGINX_VERSION='1.5.2'
ZLIB_VERSION='1.2.8'
PCRE_VERSION='8.34'
PHP_VERSION='5.3.9'
ICU_VERSION='50.1.2'
LIBMCRYPT_VERSION='2.5.8'

declare -A PHP_PECL
declare -A PHP_PECL_CONFIGURE
PHP_PECL=( ["APC"]='3.1.13' ["mongo"]='1.3.4' )
PHP_PECL_CONFIGURE=( ["APC"]='--enable-apc --enable-apc-debug' )

#设置相对目录
ROOT_DIR=${OPENSHIFT_RUNTIME_DIR}
BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
CONFIG_DIR=${OPENSHIFT_RUNTIME_DIR}/etc
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/.openshift/tmpl

#载入功能
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_nginx
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build_php

#检查nginx版本
check_nginx

#检查php版本
check_php

#检查pecl插件
for ext in "${!PHP_PECL[@]}"; do
    check_pecl ${ext} ${PHP_PECL["$ext"]} ${PHP_PECL_CONFIGURE["$ext"]};
done