#!/bin/bash

#载入全局
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

#停止nginx
echo "正在停止nginx。"
killall nginx

#停止php-fpm
echo "正在停止PHP-fpm。"
killall php-fpm

# Always succeed, otherwise OpenShift declines to run build and start
# hooks.
exit 0